version: '3'
services:
  peera-nginx:
    image: nginx
    container_name: PeerA-nginx
    volumes:
      - ./nginx/PeerA/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 444:443
    networks:
        dejima_net:
            ipv4_address: 172.30.0.2

  peera-db:
    image: ekayim/dejima-postgres:latest
    container_name: PeerA-db
    ports:
        - 54321:5432
    volumes:
        - ./db/postgresql.conf:/etc/postgresql.conf
        - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
        - ./db/setup_files:/etc/setup_files
    environment:
        - PEER_NAME=PeerA 
    networks:
        dejima_net:
            ipv4_address: 172.30.0.3

  peera-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: PeerA-proxy
    command: gunicorn -b 0.0.0.0:8000 server:app
    volumes:
        - ./proxy:/code
    ports:
        - 8001:8000
    depends_on:
        - peera-db
    environment: 
        - PEER_NAME=PeerA 
    networks:
        dejima_net:
            ipv4_address: 172.30.0.4

  peerb-nginx:
    image: nginx
    container_name: PeerB-nginx
    volumes:
      - ./nginx/PeerB/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 445:443
    networks:
        dejima_net:
            ipv4_address: 172.30.0.5

  peerb-db:
    image: ekayim/dejima-postgres:latest
    container_name: PeerB-db
    ports:
        - 54322:5432
    volumes:
        - ./db/postgresql.conf:/etc/postgresql.conf
        - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
        - ./db/setup_files:/etc/setup_files
    environment:
        - PEER_NAME=PeerB 
    networks:
        dejima_net:
            ipv4_address: 172.30.0.6

  peerb-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: PeerB-proxy
    command: gunicorn -b 0.0.0.0:8000 server:app
    volumes:
        - ./proxy:/code
    ports:
        - 8002:8000
    depends_on:
        - peerb-db
    environment: 
        - PEER_NAME=PeerB 
    networks:
        dejima_net:
            ipv4_address: 172.30.0.7

networks:
  dejima_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24