version: '3'
services:
  univ-db:
    image: ekayim/dejima-postgres:latest
    container_name: Univ-db
    environment:
        - PEER_NAME=Univ1
    ports:
        - 54321:5432
    volumes:
        - ./db/postgresql.conf:/etc/postgresql.conf
        - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
        - ./db/setup_files:/etc/setup_files
  univ-proxy:
    build: ./proxy
    container_name: Univ-proxy
    command: python3 server.py
    volumes:
        - ./proxy:/code
    ports:
        - 8001:8000
    depends_on:
        - univ1-db
    environment: 
        - PEER_NAME=Univ1