version: '3'
services:
  univ-db:
    image: ekayim/dejima-postgres:latest
    container_name: Univ-db
    ports:
        - 5432:5432
    volumes:
        - ./db/postgresql.conf:/etc/postgresql.conf
        - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
        - ./db/setup_files:/etc/setup_files
    environment:
        - PEER_NAME=Univ # Replace with your university (Osaka/ Kyoto/ Hosei)

  univ-proxy:
    build: ./proxy
    container_name: Univ-proxy
    command: python3 server.py
    volumes:
        - ./proxy:/code
    ports:
        - 8000:8000
    depends_on:
        - univ-db
    environment: 
        - PEER_NAME=Univ # Replace with your university (Osaka/ Kyoto/ Hosei)