version: '3'
services:
  univ-nginx:
    image: nginx
    container_name: Univ-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 443:443
    depends_on:
      - univ-proxy

  univ-db:
    image: ekayim/dejima-postgres:latest
    container_name: Univ-db
    ports:
        - 5432:5432
    volumes:
        - ./db/postgresql.conf:/etc/postgresql.conf
        - ./db/initialize.sh:/docker-entrypoint-initdb.d/initialize.sh
        - ./db/setup_files:/etc/setup_files
    environment:
        - PEER_NAME=Osaka # Replace with your university (Osaka/ Kyoto/ Hosei)

  univ-proxy:
    image: ekayim/dejima-proxy:latest
    container_name: Univ-proxy
    command: gunicorn -b 0.0.0.0:8000 server:app
    volumes:
        - ./proxy:/code
    ports:
        - 8000:8000
    depends_on:
        - univ-db
    environment: 
        - PEER_NAME=Osaka # Replace with your university (Osaka/ Kyoto/ Hosei)